### ISSUE TITLE
[REC] Get back to developer profile from the manager

### ISSUE THREAD

**Issue by thedamfr** [welovedevs/bug-tracker-public#1]
## Abstract :
The main usecase is to find more about a developer when you using the manager in order to send him a customized introduction request.

## Workaround :
Right now it's possible to click on the name of the developer in the row to have him appear in the header. The header is actually clickable and will lead you to the developer profile.
See Gif there after ⬇️

## Solution : 
An evolution in the product should make it easier.

**Comment by thedamfr** [comment]
User Feedback [FR]

**Comment by thedamfr** [comment]
Workaround Gif : 

![manager_to_profile_std](https://user-images.githubusercontent.com/2880446/35277922-a073ee20-0048-11e8-9a28-73a55a435607.gif)

**Comment by thomasgrivet** [comment]
Fixed !
