### ISSUE TITLE
Impossible de lire les messages via le menu de droite

### ISSUE THREAD

**Issue by sfauvart** [welovedevs/bug-tracker-public#10]
## Comportement actuel
J'ai reçu une demande de contact avec un message de la part d'un recruteur.
Lorsque je clique sur le bouton dans le menu de droite, une popup s'affiche puis disparaît aussitôt avec le menu de droite

## Comportement attendu
J'ai reçu une demande de contact avec un message de la part d'un recruteur.
Lorsque je clique sur le bouton dans le menu de droite, une popup s'affiche puis reste visible.

## Solution de contournement
On peut consulter le message en passant par le tableau de bord.

## Info techs
Linux (Ubuntu 17.10)
Chrome Version 66.0.3359.139 (Build officiel) (64 bits)
Ecran Full HD (1920 x 1080)

**Comment by thomasgrivet** [comment]
Fixed! Merci du feedback :+1:
