### ISSUE TITLE
Compétences

### ISSUE THREAD

**Issue by kallard1** [welovedevs/bug-tracker-public#11]
Il serait bien de pouvoir éditer les compétences qu'on a renseigné sur le profil, également de pouvoir tous les voir d'un seul coup d'oeil et vérifier si la compétence ne serait pas en doublon lors de l'ajout

**Comment by thomasgrivet** [comment]
Bonjour ! Merci pour le feeedback, ça tombe bien, on refait les profils développeurs :slightly_smiling_face: C'est pour bientôt !
