### ISSUE TITLE
Comportement après avoir posté un message - module de question sur les profils devs

### ISSUE THREAD

**Issue by thedamfr** [welovedevs/bug-tracker-public#14]
Le composant qui créé la réponse ou la question ne revient pas dans son état initial quand la question / réponse est postée.

Exemple :
Avant
![capture d ecran 2018-06-20 a 10 03 38](https://user-images.githubusercontent.com/2880446/41645523-8a35a020-7471-11e8-992c-5a77034be073.png)

Après
![capture d ecran 2018-06-20 a 10 03 45](https://user-images.githubusercontent.com/2880446/41645513-84a27246-7471-11e8-88ce-7cf2ec8920ae.png)

Vu par un dev qui répond :
![image 1](https://user-images.githubusercontent.com/2880446/41645529-91d48ada-7471-11e8-83c9-11495f8f2c5a.png)

Feedback : 

- Dev : PAM

**Comment by thomasgrivet** [comment]
Et l'avatar est pas le bon

**Comment by thomasgrivet** [comment]
Et le line-height est pas bon non plus
