### ISSUE TITLE
Feature Request - Fermer le panneau lateral en cliquant en dehors 

### ISSUE THREAD

**Issue by thedamfr** [welovedevs/bug-tracker-public#15]
Feature demandée par PAM

Je pense que le usecase est principalement sur mobile. La croix est complètement en haut à droite de l'écran c'est relativement une zone froide en terme de tactilité du pouce.

**Comment by pierre-aurele-martin** [comment]
Même sur desktop c'est lourd puisque le panneau est scrollable donc quand on veut le fermer, on doit : 

1/ Se rappeler qu'il faut cliquer sur la croix ;
2/ Remonter le scroll ;
3/ Clicker

L'UX communément admise pour fermer un Drawer est : 

1/ Je click / tap n'importe où à l'extérieur du composant.
