### ISSUE TITLE
Bug - Css issue in blacklist

### ISSUE THREAD

**Issue by clementdevos** [welovedevs/bug-tracker-public#19]
Hey, 

There is a css issue in the Blacklist, as depicted below, using Chrome

![image](https://user-images.githubusercontent.com/5870982/42809105-10f64e72-89b5-11e8-8ba5-7ecb9505d380.png)

**Comment by thomasgrivet** [comment]
Hey!

Fixed, going in production, thanks for the feedback :+1:
