### ISSUE TITLE
Bug - css issue in Discover

### ISSUE THREAD

**Issue by clementdevos** [welovedevs/bug-tracker-public#20]
Hey guys, 

Small align items bug here : 

![image](https://user-images.githubusercontent.com/5870982/42823424-c5b8ea7c-89dd-11e8-9191-518987dc76cd.png)

:heart:

**Comment by VincentCtr** [comment]
Hello Clement
We could not reproduce the bug here (Mac OS X El capitan + Ubuntu 18.04 with Chrome 67.0.3396.99). 
We will keep an eye on it and try again if anyone report the same issue.

**Comment by clementdevos** [comment]
Hey,

Just looked over it quickly and found that  by changing this the bug goes away.

.emoji-outer {
    /* height: inherit; */
    /* line-height: inherit; */
}

![image](https://user-images.githubusercontent.com/5870982/42926387-81cda4f6-8b31-11e8-915c-8426876f8ba1.png)
