### ISSUE TITLE
[Bug] Inputs not working

### ISSUE THREAD

**Issue by FalconPilot** [welovedevs/bug-tracker-public#21]
When editing, the user profile, some inputs do not work. I noticed the issue mostly when editing skills, adding skills, searching for skills... There is an input in the DOM, but it isn't selectable. There is a greyed-out label, still, but it cannot be interacted with.

Tested on OS X 10.13.5, on Chrome 67.0.3396.99

**Comment by VincentCtr** [comment]
Hello @FalconPilot,
Thank you for the issue. It seems to be a regression linked to a recent upgrade of some of our UI libraries. I am on it and will keep you updated.

**Comment by VincentCtr** [comment]
Hello @FalconPilot 
Bug is fixed ! Thanks for the issue.
