### ISSUE TITLE
Bug connexion [Index page]

### ISSUE THREAD

**Issue by AntoineLemichel** [welovedevs/bug-tracker-public#23]
One time on the web page index, when clicked " login " and after writing ID and password, this web site reload on the web page index, we are will must clicking again on the button " login " to gonna dashboard.

**Comment by VincentCtr** [comment]
Hello Antoine,

Thank you for the bug report, I was not able to reproduce it. Can you give me more information ? (OS, browser, account type recruiter or developer?)

Can you provide a screenshot too ? 

Thank you !

**Comment by VincentCtr** [comment]
Hello Antoine, 
Just managed to reproduce the bug ! I am working on it ;)

**Comment by VincentCtr** [comment]
Fixed ! 👍
