### ISSUE TITLE
[Translation] Home.map.companiesDialog.title is missing

### ISSUE THREAD

**Issue by jry25** [welovedevs/bug-tracker-public#24]
On the map (https://welovedevs.com/app/fr/companies/search?query=&refinementList%5Bdescription.type%5D%5B0%5D=2&configure%5BhitsPerPage%5D=6&configure%5BaroundLatLngViaIP%5D=true&configure%5BaroundPrecision%5D=20000&configure%5BaroundRadius%5D=all&type=company&searchView=map&name=&latLng=) when you click on a marker you see a dialog with a title. This title should be translated, the title is "`Home.map.companiesDialog.title is missing`".

![capture d ecran 2018-11-23 a 20 41 36](https://user-images.githubusercontent.com/1884026/48958559-29ae7c80-ef60-11e8-9746-1414e3c5f2a3.jpg)

**Comment by thedamfr** [comment]
Mercy pour le feedback @jry25 !

C'est bien dans notre backlog 👌

**Comment by qk7b** [comment]
+1

**Comment by VincentCtr** [comment]
Le fix part en prod 👍  Merci
