### ISSUE TITLE
Bouton 'voir un exemple' lors de l'inscription

### ISSUE THREAD

**Issue by MaximeConan** [welovedevs/bug-tracker-public#26]
Lorsque l'on nous propose de remplir notre profil suite à notre inscription, la page propose un lien pour voir un exemple de CV en ligne sur votre plateforme. Ce bouton ne redirige vers aucune page lorsque l'on clique dessus.

**Comment by VincentCtr** [comment]
Hello Maxime ! Merci pour le retour, le bug est corrigé 👍

**Comment by MaximeConan** [comment]
Avec plaisir :)
