### ISSUE TITLE
Bouton "ajouter tag" qui est décalé

### ISSUE THREAD

**Issue by kallard1** [welovedevs/bug-tracker-public#28]
Bonjour,

Sur la page profil en mode édition, le bouton "ajouter tag" sort du bloc

<img width="649" alt="screenshot 2019-03-08 a 15 10 55" src="https://user-images.githubusercontent.com/31655652/54033768-7c314300-41b5-11e9-9bb0-6d473656089e.png">

**Comment by clementdevos** [comment]
It will be fixed in prod tonight !
