### ISSUE TITLE
Ajout de tag qui envoi en bas de page

### ISSUE THREAD

**Issue by kallard1** [welovedevs/bug-tracker-public#29]
Bonjour,

Lors de l'ajout de tag sur l'édition du profil, on se retrouve en bas de la page après la validation

**Comment by clementdevos** [comment]
Hello !

J'ai pas reproduit ton bug, tu peux me dire si t'as toujours le soucis après la mise à jour de ce soir? 

Merci, 

Clément

**Comment by kallard1** [comment]
Salut, 

D'accord. Je viens de refaire le test (avant la mise a jour) histoire de voir si je l'ai encore et je l'ai toujours (avec Google Chrome 73).
(petite vidéo afin de montrer ce que je fais : https://youtu.be/iXaWLt_isyQ)

Je referais un test demain.

Kévin

**Comment by clementdevos** [comment]
J'arrive pas à voir ta vidéo ! :(

**Comment by kallard1** [comment]
J'ai modifié le paramètre, elle devrait être accessible :)
J'ai effectué les tests à l'instant et le problème est toujours présent.

**Comment by VincentCtr** [comment]
Salut Kévin,

On arrive pas à reproduire le bug. Désolé pour le très long temps de réponse, on travaillait sur de gros chantiers.
Est-ce que tu as toujours le soucis ?

**Comment by kallard1** [comment]
Salut Vincent,

Je viens de refaire un test et je n'ai plus ce souci. Je clos donc cette issue :)
