### ISSUE TITLE
[improve] apply

### ISSUE THREAD

**Issue by LesageYann** [welovedevs/bug-tracker-public#30]
## Problème

Quand on postule pour une entreprise, la possibilité d'avoir un message personnalisé est après avoir postuler. Si on souhaite revoir un détail de l'annonce, on ferme cette popup et on s'aperçoit trop tard ne plus pouvoir envoyer de message avec la candidature.

## Suggestion

Mettre l'input de personnalisation du message dans la première popup au dessus du bouton apply.  
Fusionner les deux popup en une permettrait de pouvoir revenir sur l'annonce avant de postuler pour réfléchir au message personnalisé.

**Comment by VincentCtr** [comment]
Merci pour le retour, effectivement c'est un retour que plusieurs développeurs nous ont fait. 

On travaille sur une solution 👍

**Comment by VincentCtr** [comment]
Cette modification a été implémentée il y a quelques mois :)
