### ISSUE TITLE
Bug - Css issue on a candidate profile

### ISSUE THREAD

**Issue by adrijere** [welovedevs/bug-tracker-public#31]
Hey,

There is a css issue in the candidate profile when I started a conversation with the candidate and I go to his profile, as depicted below, using Chrome

![bugW3D](https://user-images.githubusercontent.com/7966737/55487017-9aac2200-562d-11e9-8b10-b5c29eec5b5f.jpeg)

**Comment by adrijere** [comment]
URL: https://welovedevs.com/app/developer/guillaume-developpeur-react-native-angular-toujours-curieux-dapprendre-plus

**Comment by clementdevos** [comment]
It will be fixed in prod tonight !

**Comment by clementdevos** [comment]
Fixed
