### ISSUE TITLE
[bug] - Message non lu

### ISSUE THREAD

**Issue by kallard1** [welovedevs/bug-tracker-public#33]
Bonjour,

J'ai depuis un moment la pastille qui me dit que j'ai un message non lu alors que... non tout mes messages ont bien été lu ou un message qui devait s'adresser à moi s'est perdu en route ?

Cordialement,
Kévin

**Comment by thomasgrivet** [comment]
Je regarde ça !

**Comment by thomasgrivet** [comment]
ça devrait être bon :+1:
