### ISSUE TITLE
Crash sur la liste des candidats

### ISSUE THREAD

**Issue by pdruart** [welovedevs/bug-tracker-public#35]
Présence dans la liste des candidats de profil vide sans nom qui font crash l'app.
<img width="575" alt="Capture d’écran 2019-07-03 à 10 20 37" src="https://user-images.githubusercontent.com/11226155/60575781-6f47e900-9d7c-11e9-89e5-19498b2a2ff5.png">

Bonne journée !

**Comment by pdruart** [comment]
Petite précision cela ne ce passe que lorsqu'on clic sur "voir le profil "

**Comment by VincentCtr** [comment]
C'est résolu !
