### ISSUE TITLE
Réponse automatique conversations

### ISSUE THREAD

**Issue by pdruart** [welovedevs/bug-tracker-public#37]
Serait il possible de préciser au candidats qu'il s'agit d'une réponse automatique lors de l'envoi de ce genre de message ? 
<img width="478" alt="Capture d’écran 2019-07-03 à 10 25 48" src="https://user-images.githubusercontent.com/11226155/60576066-f85f2000-9d7c-11e9-92de-4e6b627e6237.png">

**Comment by VincentCtr** [comment]
@QTournier travaille dessus !

**Comment by VincentCtr** [comment]
C'est corrigé !
