### ISSUE TITLE
Faute de frappe

### ISSUE THREAD

**Issue by kallard1** [welovedevs/bug-tracker-public#38]
Salut,

Il y a une petite faute sur [https://welovedevs.com/app/fr/onboarding/today](https://welovedevs.com/app/fr/onboarding/today) dans la partie : `Ce que vous n'aimez pas dans votre job actuel`

`Pas assez de challange`

Je pense que c'est encore un coup des communistes mais je ne suis pas sûr.

Bonne journée

**Comment by VincentCtr** [comment]
Merci pour le retour ! C'est corrigé 👍
