### ISSUE TITLE
The company dashboard is down

### ISSUE THREAD

**Issue by ArnaudSpanneut** [welovedevs/bug-tracker-public#39]
I cannot access to the dashboard anymore.
I have an error screen displayed:

<img width="1680" alt="Capture d’écran 2019-07-26 à 10 27 17" src="https://user-images.githubusercontent.com/2766935/61937836-01b06680-af90-11e9-9f36-b380d19a7da9.png">

**Comment by VincentCtr** [comment]
Thank you for the feedback. 
We are working on it and a fix should be ready by the end of the day !
