### ISSUE TITLE
Bug: impossible d'ouvrir un profil dans le flux d'activité

### ISSUE THREAD

**Issue by domivinc** [welovedevs/bug-tracker-public#40]
Dans un flux d'activité, certaines photos de profil peuvent être en svg et dans certains cas le svg recouvre de manière transparente les autres photos de profil.
Au clic sur une photo de profil, c'est le profil avec svg qui est ouvert.
Dans l'exemple ci-dessous, le clic sur le premier élément (Martin Lutton) ouvre le profil du deuxième élément (Florian Le Merrer). Le svg de Florian recouvre la photo de Martin:

![image](https://user-images.githubusercontent.com/53612747/62370964-d3a0c880-b533-11e9-93eb-1c633608870a.png)

La solution consiste à mettre un overflow:hidden sur un des DIV contenant le svg.

**Comment by VincentCtr** [comment]
Bonjour ! Merci pour le retour je regarde ca dans l'après midi et je reviens vers toi :)
