### ISSUE TITLE
Template markup is showing on Superlike description

### ISSUE THREAD

**Issue by alex-deneuvillers** [welovedevs/bug-tracker-public#41]
Hi,

On the superlike description we can see: Developer.superlikesDialog.more, see screenshot:
<img width="603" alt="Capture d’écran 2019-10-03 à 11 01 14" src="https://user-images.githubusercontent.com/6084136/66113738-b1780500-e5cd-11e9-9a74-fe8f024c5bcf.png">

**Comment by clementdevos** [comment]
C'est fixé je pense ;)
