### ISSUE TITLE
Problème à partir de l'étape 4 de la création de profil pro'

### ISSUE THREAD

**Issue by PierreD59** [welovedevs/bug-tracker-public#42]
Bonjour, c'est pour rapport un petit bug, je suis en train de créer mon profil  professionnel et à partir de l'étape 4, ça ne veut pas continuer, j'ai beau cliquer sur l'étape suivante, rien ne se fait.

Ce soucis m'empêche d'enregistrer mes expériences professionnels pour le coup. L'étape 4 ne fonctionne ni sur Mozilla ni sur Chrome.

**Comment by clementdevos** [comment]
Bonjour Pierre, 
Tu n'est pas le seul à nous remonter le soucis, je pense que l'affichage des erreurs n'est pas assez visible sur certains écrans, on va regarder ça.

**Comment by clementdevos** [comment]
Bonjour, 

Nous avons amélioré la visibilité depuis quelque temps, je ferme ce ticket.
