### ISSUE TITLE
navbar inaccesible quand on scroll down

### ISSUE THREAD

**Issue by yatoogamii** [welovedevs/bug-tracker-public#43]
Les liens dans la navbar ne sont plus accessibles quand on scroll down sur la page recruteur : https://welovedevs.com/recruteurs/ ainsi que sur la page https://welovedevs.com/recruteurs/2019/12/05/portrait-dun-developpeur-en-teletravail-romain/. je n'ai pas testé toutes les pages mais j'imagine que le problème se trouve également ailleurs

**Comment by clementdevos** [comment]
Forwarded this to @nclsdtrz , he's in charge of this part of the site.

**Comment by VincentCtr** [comment]
Je pense que ce ticket a été fixé depuis. 

Désolé @yatoogamii pour le temps de réponse. Je pense que nous n'avons pas vu ton ticket. Est-ce que tu arrives à reproduire aujourd'hui?

**Comment by yatoogamii** [comment]
Ça a l'air d'être fixé en effet.

Je close.
