### ISSUE TITLE
Pagination on Filter Update

### ISSUE THREAD

**Issue by louisiscoding** [welovedevs/bug-tracker-public#44]
Salut l'équipe,

J'ai remarqué un comportement un peu embêtant lorsque je faisais des recherches sur welovedevs. Le scénario est le suivant :

- Chercher un mot clé pour une techno
- Incrémenter la pagination
- Affiner la recherche via les filtres (type localisation)
- La pagination est conservée même si les résultats changent.

Résultat: l'actualisation des jobs qui match fonctionne, mais n'est plus visible par l'utilisateur
Il faudrait juste reset la pagination en même temps que le refresh des jobs :D

[Démo](https://gofile.io/?c=lNFI1s)

Bonjour à l'équipe en passant 👏

**Comment by clementdevos** [comment]
J'ai ouvert le bug en interne, merci !

**Comment by clementdevos** [comment]
It should be fixed (since Apr 17th) can you confirm it's good for you?
