### ISSUE TITLE
job descriptions disappear in tablet version

### ISSUE THREAD

**Issue by OMantel1** [welovedevs/bug-tracker-public#45]
hello,
no jobs descriptions bewteen 761px and 1000px on job pages.
![welovedevs com_app_fr_job_titre-du-poste-les-tilleuls-coop-1](https://user-images.githubusercontent.com/52040897/73313222-e79b5d80-422a-11ea-99c1-f8d64e2631ac.png)
https://welovedevs.com/app/fr/job/titre-du-poste-les-tilleuls-coop-1
have a nice day.

**Comment by clementdevos** [comment]
Fixed a while ago, closing this
