### ISSUE TITLE
Avatar déformé

### ISSUE THREAD

**Issue by batiste-dek** [welovedevs/bug-tracker-public#47]
J'ai remarqué un petit bug sur cette page https://welovedevs.com/fr/tag/le-podcast/ (cf screen ci-dessous) ✌️ 

![image](https://user-images.githubusercontent.com/29843093/80573938-33fc6200-8a01-11ea-8ea0-f21ef8a44506.png)

**Comment by VincentCtr** [comment]
Merci pour le retour ! C'est fixé 👍
