### ISSUE TITLE
Orthographe

### ISSUE THREAD

**Issue by carlito767** [welovedevs/bug-tracker-public#49]
Bonjour,

Lors de la création de mon profil développeur, j'ai relevé quelques fautes d'orthographe :

![WLD1](https://user-images.githubusercontent.com/27714584/84403659-3eb43480-ac06-11ea-8e68-996d31fd2f27.png)

![WLD2](https://user-images.githubusercontent.com/27714584/84403663-3f4ccb00-ac06-11ea-8331-f0db7e573669.png)

![WLD3](https://user-images.githubusercontent.com/27714584/84403655-3e1b9e00-ac06-11ea-9ec7-04bd6e06d0cc.png)

**Comment by clementdevos** [comment]
Oula, c'est villain !

On va corriger tout ça, merci !
