### ISSUE TITLE
[Bug ?] Infinite loading UX-side

### ISSUE THREAD

**Issue by FalconPilot** [welovedevs/bug-tracker-public#5]
I found what *may* be a bug or at least an UX issue ?

So, here's what I tried : I copied a developer URL from my company's recruiter profile, then I loaded the URL when I was logged with my personal developer account. I checked the console logs :
`Error: permission_denied at /developer_anonymous_profiles/GEIEcaf4FoYy7QNkU3OJESOyQAu2: Client doesn't have permission to access the desired data.`

... However, on the interface, it displays an infinite loading animation and no feedback to the user whatsoever (which could be confusing if, say, someone tried to naively share a developer link to someone else)

Important note : this didn't happen if I was logged out (told me that "This developer doesn't exist"). It only occurs if I am logged with a developer account

**Comment by thedamfr** [comment]
I would even say that it's a feature or a missing feature 😃
Thanks for the feedback

**Comment by thomasgrivet** [comment]
I take it !

**Comment by thomasgrivet** [comment]
Fixed in the new developer profiles, currently in production :slightly_smiling_face:  Thanks for the feedback :+1:
