### ISSUE TITLE
can't access to conversation

### ISSUE THREAD

**Issue by mdespriee** [welovedevs/bug-tracker-public#50]
![image](https://user-images.githubusercontent.com/1590580/87936750-b1c98a00-ca93-11ea-875b-3c4224c0375d.png)

**Comment by clementdevos** [comment]
Hello,

We're looking into it right now. 

Cheers.

**Comment by clementdevos** [comment]
We've fixed the issue, a release will be deployed in production within  20 minutes. 

Sorry for the inconvenience. 

Clément
