### ISSUE TITLE
Tests Page - Buttons' text are misplaced

### ISSUE THREAD

**Issue by Mueslint** [welovedevs/bug-tracker-public#51]
Hello la team WLD! 

J'ai vu ce petit soucis en voyant le site, j'adore votre projet et j'ai encore peu de contribution dans l'open source.
Est-ce que vous seriez ok pour que je contribue et que je fix ça?

![image](https://user-images.githubusercontent.com/23119955/88586658-f9808080-d054-11ea-917f-22de02bbc00e.png)

ça serait un grand plaisir et honneur 🙏

**Comment by VincentCtr** [comment]
Hello @Mueslint !

Merci beaucoup d'avoir remonté ce bug ! Nous avons mis en prod une grosse évolution sur la gestion du style de l'application et on dirait que nous sommes passé à côté de ce bug.

La partie test n'est pas (encore ?) open-source, nous allons donc corriger ce bug en interne. Si tu souhaites participer à un projet open-source n'hésite pas à participer [aux profils devs](https://github.com/welovedevs/react-ultimate-resume) ! 

A très bientôt !🔥
