### ISSUE TITLE
Studies input limitation

### ISSUE THREAD

**Issue by miguelafonso** [welovedevs/bug-tracker-public#53]
It is impossible to not choose a study university that is not part of the autocomplete, and it seems they are all french.

Leving the field empty makes the form invalid, and it does not let you text freely.

<img width="887" alt="Screenshot 2020-09-14 at 20 39 42" src="https://user-images.githubusercontent.com/2726124/93124938-b2188700-f6ca-11ea-8a0d-7844f7e82b9c.png">

Is this just for a french audience? 🤔

**Comment by VincentCtr** [comment]
Hello @miguelafonso 

There is autocompletion but it is not mandatory to select something from the list and you can type a school that is not in the list.

**Comment by VincentCtr** [comment]
We have a lot of french developers and companies but the website is not only for a french audience.
