### ISSUE TITLE
Titre de section manquant dans la carte "Qui suis-je ?"

### ISSUE THREAD

**Issue by Julien-Hery** [welovedevs/bug-tracker-public#55]
Hello 🙂 

Quand je veux éditer mon profil, sur cette carte : 
<img width="712" alt="Capture d’écran 2020-10-26 à 12 00 24" src="https://user-images.githubusercontent.com/24412934/97164752-e2038180-1782-11eb-8f3d-33e493ab77d1.png">

Le titre de la section ne s'affiche pas : 
<img width="505" alt="Capture d’écran 2020-10-26 à 12 00 33" src="https://user-images.githubusercontent.com/24412934/97164758-e760cc00-1782-11eb-874e-17ddfa9429fd.png">

Selon la tournure de la phrase cela peux sembler étrange ! Est-ce qu'il ne faudrait pas afficher la question ?

**Comment by clementdevos** [comment]
J'ai ouvert l'issue sur le projet concerné, je close ici !
