### ISSUE TITLE
[ONBOARDING] Incohérence sur la sélection des technologies favorites

### ISSUE THREAD

**Issue by Julien-Hery** [welovedevs/bug-tracker-public#56]
Hello 🙂 

Ici il est indiqué qu'on peux choisir 5 technos 
<img width="720" alt="Capture d’écran 2020-10-26 à 12 03 43" src="https://user-images.githubusercontent.com/24412934/97165179-9b625700-1783-11eb-9d29-d391ced95d9d.png">

et la 6 : 
<img width="662" alt="Capture d’écran 2020-10-26 à 12 03 53" src="https://user-images.githubusercontent.com/24412934/97165225-aae1a000-1783-11eb-975d-7f12f1716d18.png">

**Comment by clementdevos** [comment]
Merci du feedback je corrige le label.

**Comment by clementdevos** [comment]
Et je fix le flex wrap sur les tags aussi.

**Comment by thedamfr** [comment]
On close @clementdevos ?

**Comment by clementdevos** [comment]
Me semble que c'est fixé.
