### ISSUE TITLE
Erreur affichage resultat test Maven

### ISSUE THREAD

**Issue by NOPROD** [welovedevs/bug-tracker-public#57]
Hello 👋,

J'ai pu remarqué un petit défaut sur la page de profil, concernant le card contenant les résultats de test.

J'ai passé un test pour Maven, mais il affiche Java.

![WhereIsMaven PNG](https://user-images.githubusercontent.com/38657472/97651647-fb474f00-1a5c-11eb-93d0-e12335a7231b.jpg)

Bon courage à vous et merci d'avance !

**Comment by VincentCtr** [comment]
Salut Amine,

Merci pour ton retour, je viens de tester plusieurs fois sur ton profil mais je n'arrive pas à reproduire. Je ne vois pas le test maven d'ajouté mais bien java et 17%. 
Est-ce que tu arrives à reproduire ? 

Bonne journée :)

**Comment by NOPROD** [comment]
Salut Vincent,

Merci pour ta réponse ^^

Le beug est encore la chez moi :/
![2](https://user-images.githubusercontent.com/38657472/98587033-e58e2100-22c9-11eb-8695-22cce6fda234.PNG)
![1](https://user-images.githubusercontent.com/38657472/98587034-e626b780-22c9-11eb-8a9b-daca15a18450.PNG)


ps: j'ai testé sous chrome, je me suis jamais log sur votre site avec ce navigateur, et j'ai 2 fois java aussi.

**Comment by VincentCtr** [comment]
Salut @NOPROD 

Désolé pour le temps de réponse, je pense que j'ai enfin compris d'ou vient ce bug. Je viens d'envoyer un fix en prod qui sera live d'ici 15 minutes.

N'hésite pas à me dire si c'est bon de ton côté et encore désolé pour le temps de traitement du bug !

**Comment by NOPROD** [comment]
Salut @VincentCtr (pas de soucis pour le temps de réponse ^^)

J'ai test de mon coté, pour le moment aucun changement, je regarderai en fin de matiné (au cas ou j'aurai du cache, peu de chance mais au cas ou ^^)

Bon courage !

**Comment by VincentCtr** [comment]
Effectivement il y a eu un petit bug sur la mise en prod, je retente un deploiement !

**Comment by VincentCtr** [comment]
Ca doit être bon 👍

**Comment by NOPROD** [comment]
@VincentCtr  Nice, c'est réglé !

Merci !
