### ISSUE TITLE
Boutons non-fonctionnels sur la page de gestion du profil

### ISSUE THREAD

**Issue by laurentdelay** [welovedevs/bug-tracker-public#58]
Hello la team! 

Le bouton "__EDITER__" en bas de la page de gestion du profil ne fonctionne pas. L'affichage change lors du click mais l'édition n'est pas déclenchée : 
![bug_bouton](https://user-images.githubusercontent.com/71564463/98423023-aa9fa980-208d-11eb-904d-0ebfcbf6251f.png)

Le bouton "__MODIFIER__" en haut de la page fonctionne quant à lui correctement. Il déclenche aussi le changement d'affichage du bouton "__EDITER__" du bas de la page.

Il y aussi les boutons du type "__Voir plus__" qui ne sont pas accessibles : le changement d'affichage les fait disparaître lors du survol. Est-ce que c'est la fonctionnalité voulue? Si oui je trouve ça assez "frustrant"
![voir_plus](https://user-images.githubusercontent.com/71564463/98423859-4500ec80-2090-11eb-99a4-a4e68e731811.png)

**Comment by VincentCtr** [comment]
Hello @laurentdelay ,

Merci pour tes retours. Effectivement le bouton editer de la carte action ne fonctionne pas ! Nous n'avions pas remarqué le bug merci beaucoup. A court terme le bouton est retiré et on verra si il faut le réactiver à l'avenir. 

Pour la "voir plus" c'est volonaire. Il permet de savoir qu'il y a quelque chose derrière la carte et est très pratique sur mobile. Si tu as une meilleure idée pour l'UX on est preneur avec plaisir ! (projet dispo en open source [ici](https://github.com/welovedevs/react-ultimate-resume))
