### ISSUE TITLE
Missing the average daily rate into CV exported to PDF

### ISSUE THREAD

**Issue by yatoogamii** [welovedevs/bug-tracker-public#59]
Hello,

when we export the CV to PDF as a freelancer we don't see the average daily rate but we see a salary of 35k (I didn't choose 35k in my profile, is that a placeholder?) so I suggest adding the average daily rate rather than the average salary.

**Comment by thedamfr** [comment]
Hey Yatoo !
Linkedin PDF parsing is definitly not optimized for freelancers !
I'm connecting this issue to #60
