### ISSUE TITLE
[Bug] Tooltip for pricing plans on the far right are hidden

### ISSUE THREAD

**Issue by FalconPilot** [welovedevs/bug-tracker-public#6]
Title says all. On the pricing page, on a 13" Macbook pro Retina (1440x900 ratio, only the DPI is doubled) screen, the tooltips on the far right are hidden by the right border of the screen.
<img width="424" alt="pricing" src="https://user-images.githubusercontent.com/9877634/37153326-a11d6b56-22dc-11e8-9887-c8cfb83985e5.png">
_The right border of the screenshot is the right border of my screen_

**Comment by thomasgrivet** [comment]
A new pricing is in production, thanks for the feedback :slightly_smiling_face:
