### ISSUE TITLE
filestackapi HTTP content during onboarding tutorial

### ISSUE THREAD

**Issue by chtitux** [welovedevs/bug-tracker-public#61]
During the onboarding tutorial, it seems some filestackapi assets are loaded with a `http://` URL. Hence the "Not secure" message in the Chrome address bar :scream: . The website URL **was** `https://welovedevs.com/app/fr/jobs?page=1` (with `https://`), "Not secure" was displayed because of non-https:// resources.

I was not able to reproduce and I did not know how to trigger the tutorial, so I leave that for you :-)

![welovedevs-http-filestackapi](https://user-images.githubusercontent.com/329467/113256694-97aaa180-92da-11eb-88fa-c8067b74bbec.png)

![welovedevs-http-onboarding](https://user-images.githubusercontent.com/329467/113256697-9a0cfb80-92da-11eb-88d5-d9b4a90ac1ee.png)

**Comment by chtitux** [comment]
In fact, clicking on "J'ai besoin d'aide" triggers the tutorial so the issue is easily reproducible.

![image](https://user-images.githubusercontent.com/329467/113257227-5961b200-92db-11eb-9494-aa828ec55710.png)

The issue seems to comes from the video asset URL being in `http://` in the [`main.js`](https://welovedevs.com/app/scripts/main-296f7ffc.2bb2a5359f085ea9e064.js) file:
![image](https://user-images.githubusercontent.com/329467/113257446-ae9dc380-92db-11eb-80b5-36716821039e.png)

You may test using `//process.filestackapi.com/egDg4GhpRPCOcaGPeZqQ` as URL, it will use the scheme of the current page (so `https://` for production, and `http://` for test if you don't have a TLS setup locally).

My tip: order a TLS certificate (on a test domain, not the prod one!) and distribute the TLS key & cert to your developers so they test the website in `https://` mode, even in development.

**Comment by VincentCtr** [comment]
Hello @chtitux,

Thank you for this very detailed bug report ! It was really to find the bug and it will be fixed in the next release (probably this morning !).
