### ISSUE TITLE
Impossible de de désinscrire de la plateforme (depuis chrome comme recommandée)

### ISSUE THREAD

**Issue by The-algar** [welovedevs/bug-tracker-public#62]
Impossible de de désinscrire de la plateforme (depuis chrome comme recommandée)

**Comment by The-algar** [comment]
merci d'effacer mon profile

**Comment by VincentCtr** [comment]
Bonjour @The-algar ,

Il y a un bouton pour supprimer vos données dans les paramètres. 

Vous pouvez retrouver la page ici : 
https://welovedevs.com/app/fr/settings/delete-account

Est-ce que cela fonctionne ?

**Comment by The-algar** [comment]
non ça ne fonctionne pas

après la demande de confirmation du MDP on a ce message
😂
Oups ! Une erreur est survenue...
Pas de panique, un membre de l'équipe a été informé et va intervenir rapidement ! [🚑]  Si l'erreur persiste essayez avec Google Chrome !
<https://github.com/welovedevs/bug-tracker-public/issues/>
REMONTER UN BUG
@+


__________________________________

ERIC CLERMONTET

GO4SOCIAL
100% Organic Customer Influence


***@***.******@***.***>

Mobile: +33 (0)6 64 65 18 91
Office: +33 (0)1 43 37 20 60
___________________________________

Ce message et toutes les pièces jointes (ci-après le "message") sont établis à l'intention exclusive de ses destinataires. Si vous recevez ce message par erreur, merci de le détruire et d'en avertir immédiatement l'expéditeur par e-mail. Toute utilisation de ce message non conforme à sa destination, toute diffusion et/ou toute publication, totale ou partielle, est interdite, sauf autorisation expresse de Go4Social. Les communications sur Internet n'étant pas sécurisées, Go4social informe qu'elle ne peut accepter aucune responsabilité quant au contenu de ce message.

This mail message and attachments (the "message") are solely intended for the addressees. It is confidential in nature. If you receive this message in error, please delete it and immediately notify the sender by e-mail. Any use other than its intended purpose, dissemination or disclosure, either whole or partial, is prohibited except if formal approval is granted. As communication on the Internet is not secure, Go4Social does not accept responsibility for the content of this message.

________________________________
De : Vincent Cotro ***@***.***>
Envoyé : jeudi 29 avril 2021 17:20
À : welovedevs/bug-tracker-public ***@***.***>
Cc : Eric M. Clermontet ***@***.***>; Mention ***@***.***>
Objet : Re: [welovedevs/bug-tracker-public] Impossible de de désinscrire de la plateforme (depuis chrome comme recommandée) (#62)


Bonjour @The-algar<https://github.com/The-algar> ,

Il y a un bouton pour supprimer vos données dans les paramètres.

Vous pouvez retrouver la page ici :
https://welovedevs.com/app/fr/settings/data-manager

Est-ce que cela fonctionne ?

**Comment by VincentCtr** [comment]
Arf bizarre je vais regarder :o

**Comment by VincentCtr** [comment]
Je viens d'envoyer un correctif, est-ce que tu peux tester dans 20 minutes ? Désolé pour le bug...

**Comment by The-algar** [comment]
hello

ça fonctionne toujours pas
maintenant on a un fech error quand on confirm avec son mot de passe dans la modale
Enter your password
To delete your account, please confirm your password. Reminder: all your data will be deleted !
FetchError
FYI


__________________________________

ERIC CLERMONTET

GO4SOCIAL
100% Organic Customer Influence


***@***.******@***.***>

Mobile: +33 (0)6 64 65 18 91
Office: +33 (0)1 43 37 20 60
___________________________________

Ce message et toutes les pièces jointes (ci-après le "message") sont établis à l'intention exclusive de ses destinataires. Si vous recevez ce message par erreur, merci de le détruire et d'en avertir immédiatement l'expéditeur par e-mail. Toute utilisation de ce message non conforme à sa destination, toute diffusion et/ou toute publication, totale ou partielle, est interdite, sauf autorisation expresse de Go4Social. Les communications sur Internet n'étant pas sécurisées, Go4social informe qu'elle ne peut accepter aucune responsabilité quant au contenu de ce message.

This mail message and attachments (the "message") are solely intended for the addressees. It is confidential in nature. If you receive this message in error, please delete it and immediately notify the sender by e-mail. Any use other than its intended purpose, dissemination or disclosure, either whole or partial, is prohibited except if formal approval is granted. As communication on the Internet is not secure, Go4Social does not accept responsibility for the content of this message.

________________________________
De : Vincent Cotro ***@***.***>
Envoyé : jeudi 29 avril 2021 17:42
À : welovedevs/bug-tracker-public ***@***.***>
Cc : Eric M. Clermontet ***@***.***>; Mention ***@***.***>
Objet : Re: [welovedevs/bug-tracker-public] Impossible de de désinscrire de la plateforme (depuis chrome comme recommandée) (#62)


Je viens d'envoyer un correctif, est-ce que tu peux tester dans 20 minutes ? Désolé pour le bug...

**Comment by VincentCtr** [comment]
Je viens de vérifier et j'ai fait une erreur. C'est réglé pour de bon ... :/ 

Si cela ne fonctionne pas tu peux envoyer un email avec ton email d'inscription sur yourfriends@welovedevs.com et je m'en occuperai manuellement.

**Comment by The-algar** [comment]
ça fonctionne toujours pas ,-(
plus de message d'erreur mais le bouton "confirm" passe de Rouge à Gris et rien ne se passe

A qui j'envoie la facture pour le debug ?

mon email ***@***.***

@+


__________________________________

ERIC CLERMONTET

GO4SOCIAL
100% Organic Customer Influence


***@***.******@***.***>

Mobile: +33 (0)6 64 65 18 91
Office: +33 (0)1 43 37 20 60
___________________________________

Ce message et toutes les pièces jointes (ci-après le "message") sont établis à l'intention exclusive de ses destinataires. Si vous recevez ce message par erreur, merci de le détruire et d'en avertir immédiatement l'expéditeur par e-mail. Toute utilisation de ce message non conforme à sa destination, toute diffusion et/ou toute publication, totale ou partielle, est interdite, sauf autorisation expresse de Go4Social. Les communications sur Internet n'étant pas sécurisées, Go4social informe qu'elle ne peut accepter aucune responsabilité quant au contenu de ce message.

This mail message and attachments (the "message") are solely intended for the addressees. It is confidential in nature. If you receive this message in error, please delete it and immediately notify the sender by e-mail. Any use other than its intended purpose, dissemination or disclosure, either whole or partial, is prohibited except if formal approval is granted. As communication on the Internet is not secure, Go4Social does not accept responsibility for the content of this message.

________________________________
De : Vincent Cotro ***@***.***>
Envoyé : vendredi 30 avril 2021 13:53
À : welovedevs/bug-tracker-public ***@***.***>
Cc : Eric M. Clermontet ***@***.***>; Mention ***@***.***>
Objet : Re: [welovedevs/bug-tracker-public] Impossible de de désinscrire de la plateforme (depuis chrome comme recommandée) (#62)


Je viens de vérifier et j'ai fait une erreur. C'est réglé pour de bon ... :/

Si cela ne fonctionne pas tu peux envoyer un email avec ton email d'inscription sur ***@***.******@***.***> et je m'en occuperai manuellement.

**Comment by The-algar** [comment]
[cid:15477ffa-3523-4f9a-8441-937c4613f72e]


__________________________________

ERIC CLERMONTET

GO4SOCIAL
100% Organic Customer Influence


***@***.******@***.***>

Mobile: +33 (0)6 64 65 18 91
Office: +33 (0)1 43 37 20 60
___________________________________

Ce message et toutes les pièces jointes (ci-après le "message") sont établis à l'intention exclusive de ses destinataires. Si vous recevez ce message par erreur, merci de le détruire et d'en avertir immédiatement l'expéditeur par e-mail. Toute utilisation de ce message non conforme à sa destination, toute diffusion et/ou toute publication, totale ou partielle, est interdite, sauf autorisation expresse de Go4Social. Les communications sur Internet n'étant pas sécurisées, Go4social informe qu'elle ne peut accepter aucune responsabilité quant au contenu de ce message.

This mail message and attachments (the "message") are solely intended for the addressees. It is confidential in nature. If you receive this message in error, please delete it and immediately notify the sender by e-mail. Any use other than its intended purpose, dissemination or disclosure, either whole or partial, is prohibited except if formal approval is granted. As communication on the Internet is not secure, Go4Social does not accept responsibility for the content of this message.

________________________________
De : Vincent Cotro ***@***.***>
Envoyé : vendredi 30 avril 2021 13:53
À : welovedevs/bug-tracker-public ***@***.***>
Cc : Eric M. Clermontet ***@***.***>; Mention ***@***.***>
Objet : Re: [welovedevs/bug-tracker-public] Impossible de de désinscrire de la plateforme (depuis chrome comme recommandée) (#62)


Je viens de vérifier et j'ai fait une erreur. C'est réglé pour de bon ... :/

Si cela ne fonctionne pas tu peux envoyer un email avec ton email d'inscription sur ***@***.******@***.***> et je m'en occuperai manuellement.

**Comment by The-algar** [comment]
[cid:f7251c2b-13ad-4f65-8b48-22ce8cca5df2]

FYI message fetch et de retour après 3 bonnes minutes d'attente

__________________________________

ERIC CLERMONTET

GO4SOCIAL
100% Organic Customer Influence


***@***.******@***.***>

Mobile: +33 (0)6 64 65 18 91
Office: +33 (0)1 43 37 20 60
___________________________________

Ce message et toutes les pièces jointes (ci-après le "message") sont établis à l'intention exclusive de ses destinataires. Si vous recevez ce message par erreur, merci de le détruire et d'en avertir immédiatement l'expéditeur par e-mail. Toute utilisation de ce message non conforme à sa destination, toute diffusion et/ou toute publication, totale ou partielle, est interdite, sauf autorisation expresse de Go4Social. Les communications sur Internet n'étant pas sécurisées, Go4social informe qu'elle ne peut accepter aucune responsabilité quant au contenu de ce message.

This mail message and attachments (the "message") are solely intended for the addressees. It is confidential in nature. If you receive this message in error, please delete it and immediately notify the sender by e-mail. Any use other than its intended purpose, dissemination or disclosure, either whole or partial, is prohibited except if formal approval is granted. As communication on the Internet is not secure, Go4Social does not accept responsibility for the content of this message.

________________________________
De : Vincent Cotro ***@***.***>
Envoyé : vendredi 30 avril 2021 13:53
À : welovedevs/bug-tracker-public ***@***.***>
Cc : Eric M. Clermontet ***@***.***>; Mention ***@***.***>
Objet : Re: [welovedevs/bug-tracker-public] Impossible de de désinscrire de la plateforme (depuis chrome comme recommandée) (#62)


Je viens de vérifier et j'ai fait une erreur. C'est réglé pour de bon ... :/

Si cela ne fonctionne pas tu peux envoyer un email avec ton email d'inscription sur ***@***.******@***.***> et je m'en occuperai manuellement.

**Comment by VincentCtr** [comment]
quand ca veut pas... heureusement qu'on est vendredi  !  Normalement c'est la bonne mais je vais t'éviter une nouvelle séance de debug et le faire pour toi ;) 

Ton email est offusqué par github est-ce que tu peux me l'envoyer en clair sur yourfriends@welovedevs.com ? 👍

**Comment by The-algar** [comment]
See you soon !
Your account has been successfuly deleted, we hope to see you again soon !


__________________________________

ERIC CLERMONTET

GO4SOCIAL
100% Organic Customer Influence


***@***.******@***.***>

Mobile: +33 (0)6 64 65 18 91
Office: +33 (0)1 43 37 20 60
___________________________________

Ce message et toutes les pièces jointes (ci-après le "message") sont établis à l'intention exclusive de ses destinataires. Si vous recevez ce message par erreur, merci de le détruire et d'en avertir immédiatement l'expéditeur par e-mail. Toute utilisation de ce message non conforme à sa destination, toute diffusion et/ou toute publication, totale ou partielle, est interdite, sauf autorisation expresse de Go4Social. Les communications sur Internet n'étant pas sécurisées, Go4social informe qu'elle ne peut accepter aucune responsabilité quant au contenu de ce message.

This mail message and attachments (the "message") are solely intended for the addressees. It is confidential in nature. If you receive this message in error, please delete it and immediately notify the sender by e-mail. Any use other than its intended purpose, dissemination or disclosure, either whole or partial, is prohibited except if formal approval is granted. As communication on the Internet is not secure, Go4Social does not accept responsibility for the content of this message.

________________________________
De : Vincent Cotro ***@***.***>
Envoyé : vendredi 30 avril 2021 14:17
À : welovedevs/bug-tracker-public ***@***.***>
Cc : Eric M. Clermontet ***@***.***>; Mention ***@***.***>
Objet : Re: [welovedevs/bug-tracker-public] Impossible de de désinscrire de la plateforme (depuis chrome comme recommandée) (#62)


quand ca veut pas... heureusement qu'on est vendredi ! Normalement c'est la bonne mais je vais t'éviter une nouvelle séance de debug et le faire pour toi ;)

Ton email est offusqué par github est-ce que tu peux me l'envoyer en clair par sur ***@***.******@***.***> ? 👍

**Comment by VincentCtr** [comment]
J'ai rarement été aussi content de voir quelqu'un partir 😄

**Comment by The-algar** [comment]
ça t'aura permis de debugger
@+


__________________________________

ERIC CLERMONTET

GO4SOCIAL
100% Organic Customer Influence


***@***.******@***.***>

Mobile: +33 (0)6 64 65 18 91
Office: +33 (0)1 43 37 20 60
___________________________________

Ce message et toutes les pièces jointes (ci-après le "message") sont établis à l'intention exclusive de ses destinataires. Si vous recevez ce message par erreur, merci de le détruire et d'en avertir immédiatement l'expéditeur par e-mail. Toute utilisation de ce message non conforme à sa destination, toute diffusion et/ou toute publication, totale ou partielle, est interdite, sauf autorisation expresse de Go4Social. Les communications sur Internet n'étant pas sécurisées, Go4social informe qu'elle ne peut accepter aucune responsabilité quant au contenu de ce message.

This mail message and attachments (the "message") are solely intended for the addressees. It is confidential in nature. If you receive this message in error, please delete it and immediately notify the sender by e-mail. Any use other than its intended purpose, dissemination or disclosure, either whole or partial, is prohibited except if formal approval is granted. As communication on the Internet is not secure, Go4Social does not accept responsibility for the content of this message.

________________________________
De : Vincent Cotro ***@***.***>
Envoyé : vendredi 30 avril 2021 14:36
À : welovedevs/bug-tracker-public ***@***.***>
Cc : Eric M. Clermontet ***@***.***>; Mention ***@***.***>
Objet : Re: [welovedevs/bug-tracker-public] Impossible de de désinscrire de la plateforme (depuis chrome comme recommandée) (#62)


J'ai rarement été aussi content de voir quelqu'un partir 😄
