### ISSUE TITLE
Oauth fail without a clear error message

### ISSUE THREAD

**Issue by Lau-po** [welovedevs/bug-tracker-public#63]
Hi,

I tried to connect after a long time and I tried using GitHub auth button but it failed with an empty error message array.

Step to reproduce:
Sign up with Google OAuth
Disconnect
Try GitHub OAuth to connect

**Comment by clementdevos** [comment]
My guess is that github login is not working altogether. 

I'll look into it.

**Comment by clementdevos** [comment]
Ok so the error was you've already had a Google Auth Account and firebase does not allow multiple providers on a single account. 
I've fixed the error handling to display this message properly. 

Thanks for spotlighting this to us. 
It should be live in the next release (tomorrow)
