### ISSUE TITLE
Ajout d’une checkbox « pas de notifications (mail/sms) le week-end »

### ISSUE THREAD

**Issue by NicolasHov** [welovedevs/bug-tracker-public#64]
Désactive l’envoi de mails/sms le week-end. Permet de garder le délai de réponse aux recruteurs si on est pas dispo du week-end.

**Comment by clementdevos** [comment]
Bonne idée, ca demande un peu de travail :sweat_smile:

**Comment by clementdevos** [comment]
Bonjour ! Oublié de répondre au ticket mais c'est implémenté depuis cet été !
