### ISSUE TITLE
Motivation de code

### ISSUE THREAD

**Issue by JPugetGil** [welovedevs/bug-tracker-public#65]
L'application m'indique que je n'ai pas de motivation de code et m'invite à le remplir. Seulement je l'ai déjà réalisé.

**Comment by VincentCtr** [comment]
Bonjour @LinkJerome ,

Merci pour ton retour et désolé pour le temps de réponse. Est-il possible de fournir un screenshot pour nous aider à reproduire le bug ? Je n'ai pas réussi pour le moment.

**Comment by JPugetGil** [comment]
Voilà les deux captures d'écrans !

![Screenshot_20210713-075238.jpg](https://user-images.githubusercontent.com/44286896/125398244-59c81980-e3af-11eb-90e0-8b3182cd3eb7.jpg)

![Screenshot_20210713-075208.jpg](https://user-images.githubusercontent.com/44286896/125398251-5d5ba080-e3af-11eb-883c-c1b5ba65f3e6.jpg)

**Comment by VincentCtr** [comment]
Ok super on va travailler dessus merci. Je reviens vers toi quand c'est corrigé !

**Comment by clementdevos** [comment]
Salut @LinkJerome, j'ai fix le soucis ! 

Merci pour le bug report !
