### ISSUE TITLE
<link rel=preload> must have a valid `as` value

### ISSUE THREAD

**Issue by tolbon** [welovedevs/bug-tracker-public#66]
Bonjour,
Dans la balise head il y a une balise 
`<link rel="preload" href="/w3d.webmanifest" as="manifest">`
Manifest n'est pas valide d'après Safari et le [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload#what_types_of_content_can_be_preloaded)

**Comment by VincentCtr** [comment]
Merci @tolbon ! C'est corrigé, le fix part en prod. N'hésite pas si tu vois autre chose 👍
