### ISSUE TITLE
petit écran pas de conversation

### ISSUE THREAD

**Issue by tolbon** [welovedevs/bug-tracker-public#67]
Bonjour sur un écran un peu petit ou moitié d'écran
Quand il n'y a pas de conversation tout se chevauche.
Plus les icônes à droite du drapeau qui sont blanc sur blanc :/

<img width="794" alt="image" src="https://user-images.githubusercontent.com/768394/125162558-e218a580-e188-11eb-905f-e8bac008ae93.png">

**Comment by VincentCtr** [comment]
Bonjour @tolbon ,

Merci pour le retour, nous allons corriger ce bug asap !

**Comment by clementdevos** [comment]
Hello j'ai corrigé ça partira en prod ce soir !
