### ISSUE TITLE
Societe unknown

### ISSUE THREAD

**Issue by tolbon** [welovedevs/bug-tracker-public#68]
Bonjour, 
J'ai remarqué une société proposé sans photo, sans rien, qui n'a pas de non et 
quand on clique dessus renvoie vers une 404

[La societe fantome](https://welovedevs.com/app/fr/company/qQaRF4eLi6gkHkCkQsYajvHUhT02) ( id : qQaRF4eLi6gkHkCkQsYajvHUhT02 )

![image](https://user-images.githubusercontent.com/768394/125445092-273cadee-fcf9-4977-94e8-8727a92b3e84.png)

**Comment by VincentCtr** [comment]
Hello,

Effectivement c'est une société qui a été supprimée ! Je vais voir si on peut faire quelque chose pour ne plus l'afficher dans les likes.

Merci pour le retour :)

**Comment by tolbon** [comment]
Je souligne juste qu'elle était proposé dans les sociétés a liké puisque j'ai pu le faire il y a 3 jours déjà dans cet état.

**Comment by clementdevos** [comment]
Hello, normalement ca sera fixé dans la prochaine MEP.

**Comment by tolbon** [comment]
C'est bon merci :)
