### ISSUE TITLE
Erreur d'orthographe en anglais

### ISSUE THREAD

**Issue by amessinger** [welovedevs/bug-tracker-public#69]
Contexte : Toutes les pages  de la version anglaise, en tant que visiteur

Actuellement, il manque un article devant "developer" :
![image](https://user-images.githubusercontent.com/3007703/129580586-f7faeeb4-1f2e-48f4-853a-9dc6fe11a232.png)

Suggestion (pour coller au "I'm an employer") :
![image](https://user-images.githubusercontent.com/3007703/129580818-96272ac0-bffc-4de9-9b2f-5785a11de0b8.png)

--
Je découvre la plateforme, elle a l'air très sympa, bravo.

**Comment by clementdevos** [comment]
C'est corrigé (un peu tard !)
