### ISSUE TITLE
Probleme d'acces (clique pour voir les details)

### ISSUE THREAD

**Issue by HABIBMBALLO** [welovedevs/bug-tracker-public#70]

**Comment by HABIBMBALLO** [comment]
Le problème est que si l'utilisateur tape l'url pour accéder au site c'est a dire la page d'accueil , il lui génère une [erreur.[](url)](https://welovedevs.com/app/fr/register)

**Comment by HABIBMBALLO** [comment]
En plus l'authentification aussi par exemple si un utilisateur veut se connecter sa ne passe pas

**Comment by clementdevos** [comment]
Bonjour ! Je ne reproduis pas d'erreur sur cette URL, pouvez vous détailler votre erreur et/ou nous envoyer une capture d'écran?
