### ISSUE TITLE
Certificat expirés pour les sub links welovedevs

### ISSUE THREAD

**Issue by NOPR9D** [welovedevs/bug-tracker-public#71]
Yop, j'espére que vous allez bien ^^

On ne peut plus acceder aux sublinks welovedevs, les liens permettant aux dev de montrer leur vitrine :(

un petit coup de certbot? :D

![image](https://user-images.githubusercontent.com/75882457/178788340-e7bf8022-b29c-4a4a-94e7-dc32274cd084.png)

ex:
https://adrien-baudet.welovedevs.com/
https://erwan-sabourin.welovedevs.com/

**Comment by clementdevos** [comment]
Bonjour!
Oula c'est un vieux ticket. 
Ca nous arrive quand on oublie de passer certbot. On aurait bien pris un certificat mais les certificats wildcard c'est cher !

C'est fixé en tout cas !

Bonne journée !
