### ISSUE TITLE
Edition image de profil | Section d'actions (boutton)

### ISSUE THREAD

**Issue by NOPR9D** [welovedevs/bug-tracker-public#72]
Hey,

Désolé pour cette issue ^^,

La liste des actions qui sont "Random !" "Fermer" "Confirmer" ne sont pas visible chez moi :/

cf:
![image](https://user-images.githubusercontent.com/75882457/179609230-c6a21ceb-ceec-4d08-9a07-d98bb33e2be3.png)
![image](https://user-images.githubusercontent.com/75882457/179609182-8b7bbcca-e0fe-4d32-bc19-8d4c01f26b38.png)

Un lien WhatsMyBrowser si ça peut aider: https://www.whatsmybrowser.org/b/5YJYA

**Comment by clementdevos** [comment]
C'est fixé (depuis quelque temps mais on a oublié de vous répondre ! )
