### ISSUE TITLE
Impossible d'accéder à l'app une fois loggé

### ISSUE THREAD

**Issue by frkgrall** [welovedevs/bug-tracker-public#76]
Hello ! Je viens de finir la création de profil, et malgré un clear cache, je ne peux pas accéder à la plateforme lorsque j'essaie de me connecter : 
![image](https://user-images.githubusercontent.com/19280920/196410992-924cb67b-e55a-49af-89ee-f6f00575cf11.png)

Bonne journée !

**Comment by VincentCtr** [comment]
Hello Franck 
On a fait une Mep un peu dans la douleur mais ca doit être réglé maintenant 🕺

**Comment by frkgrall** [comment]
Merci copain ;) !

**Comment by HellperKK** [comment]
Bonjour, depuis ce matin j'ai le même problème : aucun accès une fois connecté après tests sur firefox et chrome.

**Comment by VincentCtr** [comment]
Bonjour @HellperKK, je n'arrive pas à reproduire et personne ne nous a remonté le soucis. Est-ce que tu pourrais détailler avec un screenshot ou encore mieux une vidéo ?

**Comment by HellperKK** [comment]
Voici une vidéo montrant le problème, j'ai essayé plusieurs pages chacune renvois sur ce message.
À noter qu'en tout début de matinée le site était accessible, c'est en revenant sur l'onglet plus tard que j'ai vu le message de bug à répétition.

https://github.com/welovedevs/bug-tracker-public/assets/13782253/d36f8bf2-044c-4ec9-937f-5a22990adb8e

**Comment by VincentCtr** [comment]
C'est très bizarre ! Je reçois bien des rapports d'erreurs avec ton compte. 
L'erreur est assez obscure... Cela peut être lié à du cache, peux-tu essayer de vider le cache ? Est-ce que le problème apparait aussi en navigation privée ?

**Comment by HellperKK** [comment]
Le problème apparait aussi en navigation privée (firefox et chrome). J'ai tenté aussi de vider le cache, sans succès.

**Comment by VincentCtr** [comment]
Ok je t'envoie un email pour qu'on regarde ensemble directement, cela sera surement plus simple !
