### ISSUE TITLE
Consulter son profil en tant que développeur nous redirige vers une page d'erreur

### ISSUE THREAD

**Issue by mblampain** [welovedevs/bug-tracker-public#79]
Profil développpeur.
- Cliquer sur son avatar dans la top bar
- Cliquer sur "Profil" 

![image](https://github.com/welovedevs/bug-tracker-public/assets/55997858/a7f18c95-6edb-4bb0-9bc2-9a1664140c14)

- Redirigé vers la route **(https://welovedevs.com/app/fr/developer/)**
- Page d'erreur :

![image](https://github.com/welovedevs/bug-tracker-public/assets/55997858/815610f3-b08c-43de-b88c-d3dc35fe8bf6)

**Comment by VincentCtr** [comment]
Hello! Ca a été fixé grace à ton ticket, merci beaucoup.
